### ISSUE TITLE
http.cookiejar 是什么。。。

### ISSUE THREAD

**Issue by isanyway** [ztc1997/ChaoxingSkipSchool#1]
[root@163 ChaoxingSkipSchool]# python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import http.cookiejar
ImportError: No module named http.cookiejar

**Comment by isanyway** [comment]
好吧谷歌一下解决了23333

**Comment by isanyway** [comment]
还是有问题。。。
[root@163 ChaoxingSkipSchool]# python3 main.py  
请输入用户名： \*  
请输入密码（不显示输入）：  
正在加载...  
Traceback (most recent call last):  
  File "main.py", line 180, in <module>  
    user_info = login(username, password)  
  File "main.py", line 27, in login  
    return json_obj['msg']  
KeyError: 'msg'

**Comment by ztc1997** [comment]
这个项目已过时，不再提供支持。

**Comment by isanyway** [comment]
好吧
